### ISSUE TITLE
doesn't work as expected

### ISSUE THREAD

**Issue by BMaxV** [theanine3D/Blender-BAM-Exporter#2]
I'm on ubuntu 22.04 and I use a zipped unpacked version of blender.

When I try to export a simple object with a bone and an animation, blender freezes. Nothing gets saved.

Maybe you can test it on your end and give info which version worked for you? Also tested examples files would be awesome. Thanks!

**Comment by theanine3D** [comment]
This might be related to the newest feature I added, which automatically attempts to download the blend2bam dependency. For whatever reason, it might be stalling on that part.

I just pushed an update (0.4) that adds additional error checking, as well as a timeout to the lines that deal with running Python subprocesses. Try updating and let me know if it's still freezing. At the very least, it should now not freeze and show an error message if it's failing at any point. What is the Python path that you have set in the Blender addon prefs for this addon?

I was just able to run this new version of the addon with the latest Panda3D installed via pip, as well as blend2bam installed via pip. It ran and produced a .bam file successfully on Blender 3.5.1, Ubuntu 22.04 (Jammy Jellyfish LTS). On this Linux installation, I have the Python path set to /usr/bin/python3 in the preferences for this addon.
